import type { WordEntry } from './words';

// Order and wording follow the supplied 001–300 list. Repeated pairs remain intentional entries.
const pairs = [
  ['BDSM', 'Tinder'],
  ['Bondage', 'Privé'],
  ['Dominazione', 'Voyeurismo'],
  ['Sottomissione', 'Esibizionismo'],
  ['Sadomaso', 'Scambismo'],
  ['Collare', 'Lingerie'],
  ['Manette', 'Perizoma'],
  ['Frustino', 'Giarrettiera'],
  ['Paddle', 'Corsetto'],
  ['Benda', 'Sex toy'],
  ['Corda bondage', 'Vibratore'],
  ['Wand', 'Manette'],
  ['Plug', 'Collare'],
  ['Cock ring', 'Paddle'],
  ['Rabbit', 'Benda'],
  ['Sex toy', 'Giarrettiera'],
  ['Fetish', 'Dirty talk'],
  ['Latex', 'Pizzo'],
  ['Pelle', 'Latex'],
  ['Dominante', 'Amante'],
  ['Proibito', 'Motel'],
  ['Trasgressione', 'Privé'],
  ['Voyeurismo', 'Scandalo'],
  ['Esibizionismo', 'Segreto'],
  ['Scambismo', 'Tradimento'],
  ['Amante', 'Scappatella'],
  ['One-night stand', 'BDSM'],
  ['Escort', 'Strip club'],
  ['Lap dance', 'Privé'],
  ['Spogliarello', 'Champagne'],
  ['Lingerie', 'Maschera'],
  ['Perizoma', 'Collare'],
  ['Giarrettiera', 'Manette'],
  ['Corsetto', 'Frustino'],
  ['Pizzo', 'Bondage'],
  ['Latex', 'BDSM'],
  ['Maschera', 'Voyeurismo'],
  ['Privé', 'Hotel'],
  ['Motel', 'Scambismo'],
  ['Hotel', 'Amante'],
  ['Champagne', 'Lingerie'],
  ['Dirty talk', 'Confessione'],
  ['Fantasia proibita', 'Segreto'],
  ['Tentazione', 'Tradimento'],
  ['Gelosia', 'Possessività'],
  ['Ossessione', 'Passione'],
  ['Attrazione', 'Fetish'],
  ['Seduzione', 'Dominazione'],
  ['Provocazione', 'Esibizionismo'],
  ['Scandalo', 'Voyeurismo'],
  ['Nudità', 'Roleplay'],
  ['Roleplay', 'Maschera'],
  ['Maschera', 'Segreto'],
  ['Segreto', 'Scappatella'],
  ['Scappatella', 'Champagne'],
  ['Amante', 'Hotel'],
  ['Hotel', 'Motel'],
  ['Motel', 'Afterparty'],
  ['Afterparty', 'Privé'],
  ['Privé', 'Discoteca'],
  ['Discoteca', 'Lap dance'],
  ['Lap dance', 'Spogliarello'],
  ['Spogliarello', 'Lingerie'],
  ['Lingerie', 'Latex'],
  ['Latex', 'Pizzo'],
  ['Pizzo', 'Seta'],
  ['Seta', 'Raso'],
  ['Raso', 'Corsetto'],
  ['Corsetto', 'Giarrettiera'],
  ['Giarrettiera', 'Tacchi'],
  ['Tacchi', 'Minigonna'],
  ['Minigonna', 'Scollatura'],
  ['Scollatura', 'Décolleté'],
  ['Décolleté', 'Rossetto'],
  ['Rossetto', 'Bacio'],
  ['Bacio', 'Succhiotto'],
  ['Succhiotto', 'Morso'],
  ['Morso', 'Brividi'],
  ['Brividi', 'Adrenalina'],
  ['Adrenalina', 'Tensione'],
  ['Tensione', 'Desiderio'],
  ['Desiderio', 'Tentazione'],
  ['Tentazione', 'Peccato'],
  ['Peccato', 'Proibito'],
  ['Proibito', 'Scandalo'],
  ['Scandalo', 'Pettegolezzo'],
  ['Pettegolezzo', 'Gossip'],
  ['Gossip', 'Segreto'],
  ['Segreto', 'Confessione'],
  ['Confessione', 'Ammissione'],
  ['Flirt', 'Rimorchio'],
  ['Rimorchio', 'Tinder'],
  ['Tinder', 'Match'],
  ['Match', 'Crush'],
  ['Crush', 'Infatuazione'],
  ['Infatuazione', 'Ossessione'],
  ['Ossessione', 'Gelosia'],
  ['Gelosia', 'Possessività'],
  ['Possessività', 'Controllo'],
  ['Controllo', 'Dominazione'],
  ['Dominazione', 'Potere'],
  ['Potere', 'Sottomissione'],
  ['Sottomissione', 'Fiducia'],
  ['Fiducia', 'Intimità'],
  ['Intimità', 'Complicità'],
  ['Complicità', 'Segreto'],
  ['Segreto', 'Mistero'],
  ['Mistero', 'Maschera'],
  ['Maschera', 'Benda'],
  ['Benda', 'Manette'],
  ['Manette', 'Polsini'],
  ['Polsini', 'Collare'],
  ['Collare', 'Corda bondage'],
  ['Corda bondage', 'Paddle'],
  ['Paddle', 'Frustino'],
  ['Frustino', 'Maschera'],
  ['Maschera', 'Roleplay'],
  ['Roleplay', 'Fetish'],
  ['Fetish', 'Latex'],
  ['Latex', 'Pelle'],
  ['Pelle', 'Seta'],
  ['Seta', 'Lingerie'],
  ['Lingerie', 'Perizoma'],
  ['Perizoma', 'Corsetto'],
  ['Corsetto', 'Body'],
  ['Body', 'Reggiseno'],
  ['Reggiseno', 'Giarrettiera'],
  ['Giarrettiera', 'Calze'],
  ['Calze', 'Tacchi'],
  ['Tacchi', 'Stivali'],
  ['Stivali', 'Minigonna'],
  ['Minigonna', 'Vestito'],
  ['Vestito', 'Nudo'],
  ['Nudo', 'Specchio'],
  ['Specchio', 'Selfie'],
  ['Selfie', 'Foto'],
  ['Foto', 'Story'],
  ['Story', 'DM'],
  ['DM', 'Chat'],
  ['Chat', 'Flirt'],
  ['Flirt', 'Dirty talk'],
  ['Dirty talk', 'Sussurro'],
  ['Sussurro', 'Segreto'],
  ['Segreto', 'Fantasia'],
  ['Fantasia', 'Roleplay'],
  ['Roleplay', 'Gioco'],
  ['Gioco', 'Sfida'],
  ['Sfida', 'Tentazione'],
  ['Tentazione', 'Trasgressione'],
  ['Trasgressione', 'Regola'],
  ['Regola', 'Proibito'],
  ['Proibito', 'Scandalo'],
  ['Scandalo', 'Voyeurismo'],
  ['Voyeurismo', 'Esibizionismo'],
  ['Esibizionismo', 'Privé'],
  ['Privé', 'Club'],
  ['Club', 'VIP'],
  ['VIP', 'Champagne'],
  ['Champagne', 'Hotel'],
  ['Hotel', 'Suite'],
  ['Suite', 'Motel'],
  ['Motel', 'Notte'],
  ['Notte', 'Alba'],
  ['Alba', 'Afterparty'],
  ['Afterparty', 'Discoteca'],
  ['Discoteca', 'Party'],
  ['Party', 'Festa'],
  ['Festa', 'Cocktail'],
  ['Cocktail', 'Shot'],
  ['Shot', 'Champagne'],
  ['Champagne', 'Vino'],
  ['Vino', 'Cena'],
  ['Cena', 'Dopocena'],
  ['Dopocena', 'Appuntamento'],
  ['Appuntamento', 'Flirt'],
  ['Flirt', 'Seduzione'],
  ['Seduzione', 'Provocazione'],
  ['Provocazione', 'Fascino'],
  ['Fascino', 'Magnetismo'],
  ['Magnetismo', 'Attrazione'],
  ['Attrazione', 'Chimica'],
  ['Chimica', 'Alchimia'],
  ['Alchimia', 'Scintilla'],
  ['Scintilla', 'Tensione'],
  ['Tensione', 'Eccitazione'],
  ['Eccitazione', 'Passione'],
  ['Passione', 'Desiderio'],
  ['Desiderio', 'Voglia'],
  ['Voglia', 'Tentazione'],
  ['Tentazione', 'Fantasie'],
  ['Fantasie', 'Segreti'],
  ['Segreti', 'Confidenze'],
  ['Confidenze', 'Amante'],
  ['Amante', 'Partner'],
  ['Partner', 'Ex'],
  ['Ex', 'Tradimento'],
  ['Tradimento', 'Scappatella'],
  ['Scappatella', 'One-night stand'],
  ['One-night stand', 'Dating'],
  ['Dating', 'Tinder'],
  ['Tinder', 'Grindr'],
  ['Grindr', 'Match'],
  ['Match', 'DM'],
  ['DM', 'Numero'],
  ['Numero', 'Chiamata'],
  ['Chiamata', 'Voce'],
  ['Voce', 'Sussurro'],
  ['Sussurro', 'Dirty talk'],
  ['Dirty talk', 'Roleplay'],
  ['Roleplay', 'Fantasia'],
  ['Fantasia', 'Fetish'],
  ['Fetish', 'Voyeurismo'],
  ['Voyeurismo', 'Esibizionismo'],
  ['Esibizionismo', 'Scambismo'],
  ['Scambismo', 'Privé'],
  ['Privé', 'Club'],
  ['Club', 'Strip club'],
  ['Strip club', 'Lap dance'],
  ['Lap dance', 'Spogliarello'],
  ['Spogliarello', 'Nudità'],
  ['Nudità', 'Lingerie'],
  ['Lingerie', 'Sex toy'],
  ['Sex toy', 'Vibratore'],
  ['Vibratore', 'Wand'],
  ['Wand', 'Rabbit'],
  ['Rabbit', 'Cock ring'],
  ['Cock ring', 'Plug'],
  ['Plug', 'Ben Wa balls'],
  ['Ben Wa balls', 'Palline vaginali'],
  ['Palline vaginali', 'Anello vibrante'],
  ['Anello vibrante', 'Masturbatore'],
  ['Masturbatore', 'Sex toy'],
  ['Sex toy', 'Lubrificante'],
  ['Lubrificante', 'Olio da massaggio'],
  ['Olio da massaggio', 'Massaggio'],
  ['Massaggio', 'Spa'],
  ['Spa', 'Jacuzzi'],
  ['Jacuzzi', 'Vasca'],
  ['Vasca', 'Doccia'],
  ['Doccia', 'Hotel'],
  ['Hotel', 'Suite'],
  ['Suite', 'Candele'],
  ['Candele', 'Luci soffuse'],
  ['Luci soffuse', 'Musica'],
  ['Musica', 'Playlist'],
  ['Playlist', 'Notte'],
  ['Notte', 'Buio'],
  ['Buio', 'Camera'],
  ['Camera', 'Letto'],
  ['Letto', 'Lenzuola'],
  ['Lenzuola', 'Seta'],
  ['Seta', 'Pelle'],
  ['Pelle', 'Carezza'],
  ['Carezza', 'Tocco'],
  ['Tocco', 'Abbraccio'],
  ['Abbraccio', 'Bacio'],
  ['Bacio', 'Intimità'],
  ['Intimità', 'Complicità'],
  ['Complicità', 'Passione'],
  ['Passione', 'Estasi'],
  ['Estasi', 'Piacere'],
  ['Piacere', 'Euforia'],
  ['Euforia', 'Adrenalina'],
  ['Adrenalina', 'Brividi'],
  ['Brividi', 'Calore'],
  ['Calore', 'Bollente'],
  ['Bollente', 'Piccante'],
  ['Piccante', 'Sexy'],
  ['Sexy', 'Sensuale'],
  ['Sensuale', 'Erotico'],
  ['Erotico', 'Trasgressivo'],
  ['Trasgressivo', 'Scandaloso'],
  ['Scandaloso', 'Proibito'],
  ['Proibito', 'Segreto'],
  ['Segreto', 'Mistero'],
  ['BDSM', 'Perizoma'],
  ['Tinder', 'Corda bondage'],
  ['Bondage', 'Dirty talk'],
  ['Privé', 'Motel'],
  ['Dominazione', 'Escort'],
  ['Voyeurismo', 'Confessione'],
  ['Sottomissione', 'Attrazione'],
  ['Esibizionismo', 'Seta'],
  ['Sadomaso', 'Bacio'],
  ['Scambismo', 'Peccato'],
  ['Collare', 'Crush'],
  ['Lingerie', 'Mistero'],
  ['Manette', 'Nudo'],
  ['Perizoma', 'Sussurro'],
  ['Frustino', 'Suite'],
  ['Giarrettiera', 'Vino'],
  ['Paddle', 'Alchimia'],
  ['Corsetto', 'Partner'],
  ['Benda', 'Ben Wa balls'],
  ['Sex toy', 'Spa'],
  ['Corda bondage', 'Playlist'],
  ['Vibratore', 'Abbraccio'],
  ['Wand', 'Sexy'],
  ['Plug', 'Bondage'],
  ['Cock ring', 'Scambismo'],
] as const;

const english: Record<string, string> = {
  Abbraccio: 'hug',
  Adrenalina: 'adrenaline',
  Afterparty: 'afterparty',
  Alba: 'dawn',
  Alchimia: 'alchemy',
  Amante: 'lover',
  Ammissione: 'admission',
  'Anello vibrante': 'vibrating ring',
  Appuntamento: 'date',
  Attrazione: 'attraction',
  BDSM: 'BDSM',
  Bacio: 'kiss',
  'Ben Wa balls': 'Ben Wa balls',
  Benda: 'blindfold',
  Body: 'bodysuit',
  Bollente: 'hot',
  Bondage: 'bondage',
  Brividi: 'shivers',
  Buio: 'darkness',
  Calore: 'heat',
  Calze: 'stockings',
  Camera: 'bedroom',
  Candele: 'candles',
  Carezza: 'caress',
  Cena: 'dinner',
  Champagne: 'champagne',
  Chat: 'chat',
  Chiamata: 'call',
  Chimica: 'chemistry',
  Club: 'club',
  'Cock ring': 'cock ring',
  Cocktail: 'cocktail',
  Collare: 'collar',
  Complicità: 'connection',
  Confessione: 'confession',
  Confidenze: 'confidences',
  Controllo: 'control',
  'Corda bondage': 'bondage rope',
  Corsetto: 'corset',
  Crush: 'crush',
  DM: 'DM',
  Dating: 'dating',
  Desiderio: 'desire',
  'Dirty talk': 'dirty talk',
  Discoteca: 'nightclub',
  Doccia: 'shower',
  Dominante: 'dominant',
  Dominazione: 'domination',
  Dopocena: 'after-dinner drinks',
  Décolleté: 'cleavage',
  Eccitazione: 'arousal',
  Erotico: 'erotic',
  Escort: 'escort',
  Esibizionismo: 'exhibitionism',
  Estasi: 'ecstasy',
  Euforia: 'euphoria',
  Ex: 'ex',
  Fantasia: 'fantasy',
  'Fantasia proibita': 'forbidden fantasy',
  Fantasie: 'fantasies',
  Fascino: 'charm',
  Festa: 'celebration',
  Fetish: 'fetish',
  Fiducia: 'trust',
  Flirt: 'flirt',
  Foto: 'photo',
  Frustino: 'riding crop',
  Gelosia: 'jealousy',
  Giarrettiera: 'garter belt',
  Gioco: 'game',
  Gossip: 'gossip',
  Grindr: 'Grindr',
  Hotel: 'hotel',
  Infatuazione: 'infatuation',
  Intimità: 'intimacy',
  Jacuzzi: 'hot tub',
  'Lap dance': 'lap dance',
  Latex: 'latex',
  Lenzuola: 'sheets',
  Letto: 'bed',
  Lingerie: 'lingerie',
  Lubrificante: 'lubricant',
  'Luci soffuse': 'dim lights',
  Magnetismo: 'magnetism',
  Manette: 'handcuffs',
  Maschera: 'mask',
  Massaggio: 'massage',
  Masturbatore: 'masturbator',
  Match: 'match',
  Minigonna: 'miniskirt',
  Mistero: 'mystery',
  Morso: 'bite',
  Motel: 'motel',
  Musica: 'music',
  Notte: 'night',
  Nudità: 'nudity',
  Nudo: 'nude',
  Numero: 'phone number',
  'Olio da massaggio': 'massage oil',
  'One-night stand': 'one-night stand',
  Ossessione: 'obsession',
  Paddle: 'paddle',
  'Palline vaginali': 'vaginal balls',
  Partner: 'partner',
  Party: 'party',
  Passione: 'passion',
  Peccato: 'sin',
  Pelle: 'skin',
  Perizoma: 'thong',
  Pettegolezzo: 'rumor',
  Piacere: 'pleasure',
  Piccante: 'spicy',
  Pizzo: 'lace',
  Playlist: 'playlist',
  Plug: 'plug',
  Polsini: 'cuffs',
  Possessività: 'possessiveness',
  Potere: 'power',
  Privé: 'private room',
  Proibito: 'forbidden',
  Provocazione: 'provocation',
  Rabbit: 'rabbit',
  Raso: 'satin',
  Reggiseno: 'bra',
  Regola: 'rule',
  Rimorchio: 'pickup',
  Roleplay: 'roleplay',
  Rossetto: 'lipstick',
  Sadomaso: 'sadomasochism',
  Scambismo: 'swinging',
  Scandalo: 'scandal',
  Scandaloso: 'scandalous',
  Scappatella: 'fling',
  Scintilla: 'spark',
  Scollatura: 'neckline',
  Seduzione: 'seduction',
  Segreti: 'secrets',
  Segreto: 'secret',
  Selfie: 'selfie',
  Sensuale: 'sensual',
  Seta: 'silk',
  'Sex toy': 'sex toy',
  Sexy: 'sexy',
  Sfida: 'dare',
  Shot: 'shot',
  Sottomissione: 'submission',
  Spa: 'spa',
  Specchio: 'mirror',
  Spogliarello: 'striptease',
  Stivali: 'boots',
  Story: 'story',
  'Strip club': 'strip club',
  Succhiotto: 'hickey',
  Suite: 'suite',
  Sussurro: 'whisper',
  Tacchi: 'heels',
  Tensione: 'tension',
  Tentazione: 'temptation',
  Tinder: 'Tinder',
  Tocco: 'touch',
  Tradimento: 'betrayal',
  Trasgressione: 'transgression',
  Trasgressivo: 'transgressive',
  VIP: 'VIP',
  Vasca: 'bathtub',
  Vestito: 'dress',
  Vibratore: 'vibrator',
  Vino: 'wine',
  Voce: 'voice',
  Voglia: 'longing',
  Voyeurismo: 'voyeurism',
  Wand: 'wand',
};

function translate(term: string): string {
  const value = english[term];
  if (!value) throw new Error(`Missing Spicy 18+ translation: ${term}`);
  return value;
}

export const spicy18Words: WordEntry[] = pairs.map(([word, hint]) => ({
  word, hint, wordEn: translate(word), hintEn: translate(hint), category: 'spicy_18',
}));
