export type WordEntry = {
  word: string;
  hint: string;
  wordEn: string;
  hintEn: string;
  category: string;
};

export const categories = [
  "Cibo",
  "Luoghi",
  "Oggetti",
  "Animali",
  "Sport",
  "Cinema",
] as const;

export const words: WordEntry[] = [
  // Cibo
  { word: "pizza", hint: "forno", wordEn: "pizza", hintEn: "oven", category: "Cibo" },
  { word: "pasta", hint: "sugo", wordEn: "pasta", hintEn: "sauce", category: "Cibo" },
  { word: "risotto", hint: "padella", wordEn: "risotto", hintEn: "pan", category: "Cibo" },
  { word: "lasagna", hint: "pranzo", wordEn: "lasagna", hintEn: "lunch", category: "Cibo" },
  { word: "gelato", hint: "estate", wordEn: "gelato", hintEn: "summer", category: "Cibo" },
  { word: "tiramisù", hint: "dessert", wordEn: "tiramisu", hintEn: "dessert", category: "Cibo" },
  { word: "panino", hint: "pausa", wordEn: "sandwich", hintEn: "break", category: "Cibo" },
  { word: "insalata", hint: "verdure", wordEn: "salad", hintEn: "vegetables", category: "Cibo" },
  { word: "minestra", hint: "inverno", wordEn: "soup", hintEn: "winter", category: "Cibo" },
  { word: "polenta", hint: "montagna", wordEn: "polenta", hintEn: "mountain", category: "Cibo" },
  { word: "mozzarella", hint: "latticini", wordEn: "mozzarella", hintEn: "dairy", category: "Cibo" },
  { word: "parmigiano", hint: "grattugia", wordEn: "parmesan", hintEn: "grater", category: "Cibo" },
  { word: "prosciutto", hint: "affettato", wordEn: "prosciutto", hintEn: "sliced", category: "Cibo" },
  { word: "salsiccia", hint: "griglia", wordEn: "sausage", hintEn: "grill", category: "Cibo" },
  { word: "frittata", hint: "colazione", wordEn: "omelet", hintEn: "breakfast", category: "Cibo" },
  { word: "biscotto", hint: "merenda", wordEn: "cookie", hintEn: "snack", category: "Cibo" },
  { word: "cioccolato", hint: "dolce", wordEn: "chocolate", hintEn: "sweet", category: "Cibo" },
  { word: "fragola", hint: "giardino", wordEn: "strawberry", hintEn: "garden", category: "Cibo" },
  { word: "arancia", hint: "agrumi", wordEn: "orange", hintEn: "citrus", category: "Cibo" },
  { word: "limone", hint: "cucina", wordEn: "lemon", hintEn: "kitchen", category: "Cibo" },

  // Luoghi
  { word: "scuola", hint: "lezioni", wordEn: "school", hintEn: "lessons", category: "Luoghi" },
  { word: "ospedale", hint: "medico", wordEn: "hospital", hintEn: "doctor", category: "Luoghi" },
  { word: "stazione", hint: "treno", wordEn: "station", hintEn: "train", category: "Luoghi" },
  { word: "aeroporto", hint: "viaggio", wordEn: "airport", hintEn: "travel", category: "Luoghi" },
  { word: "biblioteca", hint: "silenzio", wordEn: "library", hintEn: "quiet", category: "Luoghi" },
  { word: "museo", hint: "arte", wordEn: "museum", hintEn: "art", category: "Luoghi" },
  { word: "teatro", hint: "spettacolo", wordEn: "theater", hintEn: "show", category: "Luoghi" },
  { word: "ristorante", hint: "menu", wordEn: "restaurant", hintEn: "menu", category: "Luoghi" },
  { word: "supermercato", hint: "spesa", wordEn: "supermarket", hintEn: "groceries", category: "Luoghi" },
  { word: "parco", hint: "panchina", wordEn: "park", hintEn: "bench", category: "Luoghi" },
  { word: "spiaggia", hint: "ombrellone", wordEn: "beach", hintEn: "umbrella", category: "Luoghi" },
  { word: "montagna", hint: "sentiero", wordEn: "mountain", hintEn: "trail", category: "Luoghi" },
  { word: "castello", hint: "re", wordEn: "castle", hintEn: "king", category: "Luoghi" },
  { word: "chiesa", hint: "campana", wordEn: "church", hintEn: "bell", category: "Luoghi" },
  { word: "mercato", hint: "bancarella", wordEn: "market", hintEn: "stall", category: "Luoghi" },
  { word: "palestra", hint: "allenamento", wordEn: "gym", hintEn: "workout", category: "Luoghi" },
  { word: "ufficio", hint: "lavoro", wordEn: "office", hintEn: "work", category: "Luoghi" },
  { word: "farmacia", hint: "ricetta", wordEn: "pharmacy", hintEn: "prescription", category: "Luoghi" },
  { word: "albergo", hint: "camera", wordEn: "hotel", hintEn: "room", category: "Luoghi" },
  { word: "stadio", hint: "tifosi", wordEn: "stadium", hintEn: "fans", category: "Luoghi" },

  // Oggetti
  { word: "sedia", hint: "stanza", wordEn: "chair", hintEn: "room", category: "Oggetti" },
  { word: "tavolo", hint: "pranzo", wordEn: "table", hintEn: "lunch", category: "Oggetti" },
  { word: "ombrello", hint: "pioggia", wordEn: "umbrella", hintEn: "rain", category: "Oggetti" },
  { word: "zaino", hint: "scuola", wordEn: "backpack", hintEn: "school", category: "Oggetti" },
  { word: "orologio", hint: "tempo", wordEn: "clock", hintEn: "time", category: "Oggetti" },
  { word: "telefono", hint: "chiamata", wordEn: "phone", hintEn: "call", category: "Oggetti" },
  { word: "computer", hint: "schermo", wordEn: "computer", hintEn: "screen", category: "Oggetti" },
  { word: "lampada", hint: "luce", wordEn: "lamp", hintEn: "light", category: "Oggetti" },
  { word: "specchio", hint: "riflesso", wordEn: "mirror", hintEn: "reflection", category: "Oggetti" },
  { word: "valigia", hint: "vacanza", wordEn: "suitcase", hintEn: "vacation", category: "Oggetti" },
  { word: "chiave", hint: "serratura", wordEn: "key", hintEn: "lock", category: "Oggetti" },
  { word: "bicchiere", hint: "acqua", wordEn: "glass", hintEn: "water", category: "Oggetti" },
  { word: "forchetta", hint: "cucina", wordEn: "fork", hintEn: "kitchen", category: "Oggetti" },
  { word: "coltello", hint: "taglio", wordEn: "knife", hintEn: "cutting", category: "Oggetti" },
  { word: "martello", hint: "chiodo", wordEn: "hammer", hintEn: "nail", category: "Oggetti" },
  { word: "cuscino", hint: "letto", wordEn: "pillow", hintEn: "bed", category: "Oggetti" },
  { word: "coperta", hint: "inverno", wordEn: "blanket", hintEn: "winter", category: "Oggetti" },
  { word: "candela", hint: "fiamma", wordEn: "candle", hintEn: "flame", category: "Oggetti" },
  { word: "penna", hint: "scrittura", wordEn: "pen", hintEn: "writing", category: "Oggetti" },
  { word: "bicicletta", hint: "pedale", wordEn: "bicycle", hintEn: "pedal", category: "Oggetti" },

  // Animali
  { word: "cane", hint: "guinzaglio", wordEn: "dog", hintEn: "leash", category: "Animali" },
  { word: "gatto", hint: "finestra", wordEn: "cat", hintEn: "window", category: "Animali" },
  { word: "cavallo", hint: "sella", wordEn: "horse", hintEn: "saddle", category: "Animali" },
  { word: "mucca", hint: "fattoria", wordEn: "cow", hintEn: "farm", category: "Animali" },
  { word: "pecora", hint: "lana", wordEn: "sheep", hintEn: "wool", category: "Animali" },
  { word: "capra", hint: "campanaccio", wordEn: "goat", hintEn: "bell", category: "Animali" },
  { word: "maiale", hint: "fango", wordEn: "pig", hintEn: "mud", category: "Animali" },
  { word: "gallina", hint: "uovo", wordEn: "hen", hintEn: "egg", category: "Animali" },
  { word: "coniglio", hint: "carota", wordEn: "rabbit", hintEn: "carrot", category: "Animali" },
  { word: "leone", hint: "savana", wordEn: "lion", hintEn: "savanna", category: "Animali" },
  { word: "tigre", hint: "strisce", wordEn: "tiger", hintEn: "stripes", category: "Animali" },
  { word: "elefante", hint: "zoo", wordEn: "elephant", hintEn: "zoo", category: "Animali" },
  { word: "giraffa", hint: "collo", wordEn: "giraffe", hintEn: "neck", category: "Animali" },
  { word: "scimmia", hint: "giungla", wordEn: "monkey", hintEn: "jungle", category: "Animali" },
  { word: "delfino", hint: "mare", wordEn: "dolphin", hintEn: "sea", category: "Animali" },
  { word: "balena", hint: "oceano", wordEn: "whale", hintEn: "ocean", category: "Animali" },
  { word: "pinguino", hint: "ghiaccio", wordEn: "penguin", hintEn: "ice", category: "Animali" },
  { word: "aquila", hint: "cielo", wordEn: "eagle", hintEn: "sky", category: "Animali" },
  { word: "tartaruga", hint: "guscio", wordEn: "turtle", hintEn: "shell", category: "Animali" },
  { word: "farfalla", hint: "fiore", wordEn: "butterfly", hintEn: "flower", category: "Animali" },

  // Sport
  { word: "calcio", hint: "stadio", wordEn: "soccer", hintEn: "stadium", category: "Sport" },
  { word: "basket", hint: "canestro", wordEn: "basketball", hintEn: "hoop", category: "Sport" },
  { word: "tennis", hint: "racchetta", wordEn: "tennis", hintEn: "racket", category: "Sport" },
  { word: "pallavolo", hint: "rete", wordEn: "volleyball", hintEn: "net", category: "Sport" },
  { word: "nuoto", hint: "piscina", wordEn: "swimming", hintEn: "pool", category: "Sport" },
  { word: "ciclismo", hint: "pedalata", wordEn: "cycling", hintEn: "pedaling", category: "Sport" },
  { word: "atletica", hint: "pista", wordEn: "athletics", hintEn: "track", category: "Sport" },
  { word: "ginnastica", hint: "equilibrio", wordEn: "gymnastics", hintEn: "balance", category: "Sport" },
  { word: "scherma", hint: "maschera", wordEn: "fencing", hintEn: "mask", category: "Sport" },
  { word: "judo", hint: "kimono", wordEn: "judo", hintEn: "kimono", category: "Sport" },
  { word: "karate", hint: "cintura", wordEn: "karate", hintEn: "belt", category: "Sport" },
  { word: "sci", hint: "neve", wordEn: "skiing", hintEn: "snow", category: "Sport" },
  { word: "snowboard", hint: "montagna", wordEn: "snowboarding", hintEn: "mountain", category: "Sport" },
  { word: "pattinaggio", hint: "ghiaccio", wordEn: "skating", hintEn: "ice", category: "Sport" },
  { word: "rugby", hint: "ovale", wordEn: "rugby", hintEn: "oval", category: "Sport" },
  { word: "golf", hint: "buca", wordEn: "golf", hintEn: "hole", category: "Sport" },
  { word: "pallanuoto", hint: "acqua", wordEn: "water polo", hintEn: "water", category: "Sport" },
  { word: "arrampicata", hint: "parete", wordEn: "climbing", hintEn: "wall", category: "Sport" },
  { word: "canottaggio", hint: "remi", wordEn: "rowing", hintEn: "oars", category: "Sport" },
  { word: "equitazione", hint: "cavallo", wordEn: "horse riding", hintEn: "horse", category: "Sport" },

  // Cinema
  { word: "attore", hint: "palco", wordEn: "actor", hintEn: "stage", category: "Cinema" },
  { word: "regista", hint: "telecamera", wordEn: "director", hintEn: "camera", category: "Cinema" },
  { word: "scena", hint: "inquadratura", wordEn: "scene", hintEn: "framing", category: "Cinema" },
  { word: "trama", hint: "mistero", wordEn: "plot", hintEn: "mystery", category: "Cinema" },
  { word: "pellicola", hint: "archivio", wordEn: "film", hintEn: "archive", category: "Cinema" },
  { word: "biglietto", hint: "spettatore", wordEn: "ticket", hintEn: "audience member", category: "Cinema" },
  { word: "popcorn", hint: "snack", wordEn: "popcorn", hintEn: "snack", category: "Cinema" },
  { word: "proiettore", hint: "schermo", wordEn: "projector", hintEn: "screen", category: "Cinema" },
  { word: "copione", hint: "dialogo", wordEn: "script", hintEn: "dialogue", category: "Cinema" },
  { word: "set", hint: "ciak", wordEn: "set", hintEn: "clapperboard", category: "Cinema" },
  { word: "costume", hint: "personaggio", wordEn: "costume", hintEn: "character", category: "Cinema" },
  { word: "colonna sonora", hint: "musica", wordEn: "soundtrack", hintEn: "music", category: "Cinema" },
  { word: "premio", hint: "festival", wordEn: "award", hintEn: "festival", category: "Cinema" },
  { word: "detective", hint: "indagine", wordEn: "detective", hintEn: "investigation", category: "Cinema" },
  { word: "astronauta", hint: "spazio", wordEn: "astronaut", hintEn: "space", category: "Cinema" },
  { word: "vampiro", hint: "notte", wordEn: "vampire", hintEn: "night", category: "Cinema" },
  { word: "robot", hint: "futuro", wordEn: "robot", hintEn: "future", category: "Cinema" },
  { word: "pirata", hint: "tesoro", wordEn: "pirate", hintEn: "treasure", category: "Cinema" },
  { word: "principessa", hint: "castello", wordEn: "princess", hintEn: "castle", category: "Cinema" },
  { word: "supereroe", hint: "maschera", wordEn: "superhero", hintEn: "mask", category: "Cinema" },
];
